language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

addons:
  postgresql: "9.3"

before_script:
  - mysql -e 'create database e4s_test_mysql;'
  - psql -c 'create database e4s_test_postgres;' -U postgres
